### ISSUE TITLE
priority_plugins default config is invalid

### ISSUE THREAD

**Issue by khyperia** [magfest/ubersystem-puppet#125]
The issue is that priority_plugins is a string_list, which when it contains one element, must end with a comma (`key = value,`). This makes parsing the config fail when running the server on a default config.

This PR had it right:

https://github.com/magfest/ubersystem-puppet/pull/63

This PR reverted the above PR:

https://github.com/magfest/ubersystem-puppet/pull/64

This PR reimplemented the first PR, incorrectly:

https://github.com/magfest/ubersystem-puppet/pull/87

**Comment by EliAndrewC** [comment]
Just opened a PR for this - thanks @khyperia and sorry for the hassle getting your dev environment set up!
