### ISSUE TITLE
'guest' plugin puppet module errors when no directory named 'bands' present

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem-puppet#177]
some of the special-case logic that we added which handles the rename of the 'bands' plugin to 'guests' is error'ing out when a directory named 'bands' doesn't exist

This is repro'able with a fresh deploy, but also I am guessing it'll probably happen if we delete the 'guests' and 'bands' plugin dirs and re-run a deploy.

specific line that errors:
```
Error: /Stage[main]/Uber::Plugin_guests/File[/home/vagrant/uber/sideboard/plugins/guests]: Could not evaluate: Could not retrieve information from environment production source(s) file:///home/vagrant/uber/sideboard/plugins/bands, file:///home/vagrant/uber/sideboard/plugins/guests
```

which is https://github.com/magfest/ubersystem-puppet/blob/master/manifests/plugin_guests.pp#L40

this blocks new users from doing a deploy

**Comment by RobRuana** [comment]
The puppet deploy will succeed if EITHER the "guests" OR the "bands" directory exist, but it will fail if they are both missing. That explains why the deploy still works in production, which no longer has a "bands" directory.
